server:
  port: 5000
  servlet:
    context-path: /vaale-store-service

spring:
  # ===============================
  # DATABASE CONNECTION
  # ===============================
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 45000 # Tiempo de espera en milisegundos
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 45000
      leak-detection-threshold: 45000

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    hibernate:
      # To be updated in real production usage!
      ddl-auto: none
    show-sql: false

  jmx:
    default_domain: co.vaale.store.service

# ===============================
# Spring doc
# ===============================
springdoc:
  version: 1.5.1
  api-docs:
    path: /swagger-ui.html
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  show-actuator: true

jackson:
  date-format: co.vaale.store.RFC3339DateFormat
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false

springfox:
  documentation:
    open-api:
      v3:
        path: api-docs


